/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface OrganismAlbumArt {
    }
    interface OrganismFooter {
    }
    interface OrganismHeader {
        "backHref": any;
    }
    interface OrganismMenu {
    }
    interface PageContact {
    }
    interface PageHome {
    }
    interface PageSong {
    }
    interface PageSongs {
    }
    interface PageVideo {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLOrganismAlbumArtElement extends Components.OrganismAlbumArt, HTMLStencilElement {
    }
    var HTMLOrganismAlbumArtElement: {
        prototype: HTMLOrganismAlbumArtElement;
        new (): HTMLOrganismAlbumArtElement;
    };
    interface HTMLOrganismFooterElement extends Components.OrganismFooter, HTMLStencilElement {
    }
    var HTMLOrganismFooterElement: {
        prototype: HTMLOrganismFooterElement;
        new (): HTMLOrganismFooterElement;
    };
    interface HTMLOrganismHeaderElement extends Components.OrganismHeader, HTMLStencilElement {
    }
    var HTMLOrganismHeaderElement: {
        prototype: HTMLOrganismHeaderElement;
        new (): HTMLOrganismHeaderElement;
    };
    interface HTMLOrganismMenuElement extends Components.OrganismMenu, HTMLStencilElement {
    }
    var HTMLOrganismMenuElement: {
        prototype: HTMLOrganismMenuElement;
        new (): HTMLOrganismMenuElement;
    };
    interface HTMLPageContactElement extends Components.PageContact, HTMLStencilElement {
    }
    var HTMLPageContactElement: {
        prototype: HTMLPageContactElement;
        new (): HTMLPageContactElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageSongElement extends Components.PageSong, HTMLStencilElement {
    }
    var HTMLPageSongElement: {
        prototype: HTMLPageSongElement;
        new (): HTMLPageSongElement;
    };
    interface HTMLPageSongsElement extends Components.PageSongs, HTMLStencilElement {
    }
    var HTMLPageSongsElement: {
        prototype: HTMLPageSongsElement;
        new (): HTMLPageSongsElement;
    };
    interface HTMLPageVideoElement extends Components.PageVideo, HTMLStencilElement {
    }
    var HTMLPageVideoElement: {
        prototype: HTMLPageVideoElement;
        new (): HTMLPageVideoElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "organism-album-art": HTMLOrganismAlbumArtElement;
        "organism-footer": HTMLOrganismFooterElement;
        "organism-header": HTMLOrganismHeaderElement;
        "organism-menu": HTMLOrganismMenuElement;
        "page-contact": HTMLPageContactElement;
        "page-home": HTMLPageHomeElement;
        "page-song": HTMLPageSongElement;
        "page-songs": HTMLPageSongsElement;
        "page-video": HTMLPageVideoElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface OrganismAlbumArt {
    }
    interface OrganismFooter {
    }
    interface OrganismHeader {
        "backHref"?: any;
    }
    interface OrganismMenu {
    }
    interface PageContact {
    }
    interface PageHome {
    }
    interface PageSong {
    }
    interface PageSongs {
    }
    interface PageVideo {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "organism-album-art": OrganismAlbumArt;
        "organism-footer": OrganismFooter;
        "organism-header": OrganismHeader;
        "organism-menu": OrganismMenu;
        "page-contact": PageContact;
        "page-home": PageHome;
        "page-song": PageSong;
        "page-songs": PageSongs;
        "page-video": PageVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "organism-album-art": LocalJSX.OrganismAlbumArt & JSXBase.HTMLAttributes<HTMLOrganismAlbumArtElement>;
            "organism-footer": LocalJSX.OrganismFooter & JSXBase.HTMLAttributes<HTMLOrganismFooterElement>;
            "organism-header": LocalJSX.OrganismHeader & JSXBase.HTMLAttributes<HTMLOrganismHeaderElement>;
            "organism-menu": LocalJSX.OrganismMenu & JSXBase.HTMLAttributes<HTMLOrganismMenuElement>;
            "page-contact": LocalJSX.PageContact & JSXBase.HTMLAttributes<HTMLPageContactElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-song": LocalJSX.PageSong & JSXBase.HTMLAttributes<HTMLPageSongElement>;
            "page-songs": LocalJSX.PageSongs & JSXBase.HTMLAttributes<HTMLPageSongsElement>;
            "page-video": LocalJSX.PageVideo & JSXBase.HTMLAttributes<HTMLPageVideoElement>;
        }
    }
}
